CREATE TABLE IF NOT EXISTS T_SYS_CONFIG (
    CONFIG_CODE VARCHAR(80) NOT NULL,
    CONFIG_NAME VARCHAR(200),
    REMARK VARCHAR(1000),
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (CONFIG_CODE)
);

COMMENT ON TABLE T_SYS_CONFIG IS '系统配置主表';

CREATE TABLE IF NOT EXISTS T_SYS_CONFIG_DETAIL (
    CONFIG_CODE VARCHAR(80) NOT NULL,
    DETAIL_CODE VARCHAR(80) NOT NULL,
    DETAIL_VALUE TEXT,
    REMARK VARCHAR(1000),
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (CONFIG_CODE, DETAIL_CODE)
);

COMMENT ON TABLE T_SYS_CONFIG_DETAIL IS '系统配置明细表';

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_TASK (
    TASK_ID VARCHAR(80) NOT NULL,
    APP_NAME VARCHAR(100) NOT NULL,
    ENV VARCHAR(30) NOT NULL,
    PATCH_NAME VARCHAR(300),
    PATCH_SHA256 VARCHAR(128),
    RELOAD_TYPE VARCHAR(30),
    PERSIST_ON_RESTART VARCHAR(1) DEFAULT 'N',
    TASK_REMARK VARCHAR(1000),
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (TASK_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_TASK IS '集群热重载任务主表';
CREATE INDEX IF NOT EXISTS IDX_HOT_RELOAD_TASK_01 ON T_HOT_RELOAD_TASK (ENV, APP_NAME);

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_TASK_INSTANCE (
    TASK_INSTANCE_ID VARCHAR(80) NOT NULL,
    TASK_ID VARCHAR(80) NOT NULL,
    APP_NAME VARCHAR(100) NOT NULL,
    ENV VARCHAR(30) NOT NULL,
    IP VARCHAR(64) NOT NULL,
    EXECUTE_TYPE VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    STATUS VARCHAR(30) NOT NULL,
    ERROR_CODE VARCHAR(100),
    ERROR_MESSAGE VARCHAR(2000),
    RELOAD_RESULT TEXT,
    RETRY_COUNT INTEGER DEFAULT 0,
    RECEIVE_TIME TIMESTAMP,
    START_TIME TIMESTAMP,
    FINISH_TIME TIMESTAMP,
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (TASK_INSTANCE_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_TASK_INSTANCE IS '集群热重载节点执行日志表';
CREATE INDEX IF NOT EXISTS IDX_HOT_RELOAD_TASK_INST_01 ON T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_HOT_RELOAD_TASK_INST_02 ON T_HOT_RELOAD_TASK_INSTANCE (IP);
CREATE INDEX IF NOT EXISTS IDX_HOT_RELOAD_TASK_INST_03 ON T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, IP, EXECUTE_TYPE);

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_FILE (
    FILE_ID VARCHAR(80) NOT NULL,
    TASK_ID VARCHAR(80) NOT NULL,
    FILE_NAME VARCHAR(300),
    FILE_TYPE VARCHAR(30) NOT NULL,
    BEAN_NAME VARCHAR(300),
    CLASS_NAME VARCHAR(500),
    FILE_SHA256 VARCHAR(128),
    FILE_CONTENT BYTEA NOT NULL,
    CREATED_BY VARCHAR(50),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (FILE_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_FILE IS '集群热重载补丁文件表';
CREATE INDEX IF NOT EXISTS IDX_HOT_RELOAD_FILE_01 ON T_HOT_RELOAD_FILE (TASK_ID);
