CREATE TABLE T_SYS_CONFIG (
    CONFIG_CODE VARCHAR2(80 CHAR) NOT NULL,
    CONFIG_NAME VARCHAR2(200 CHAR),
    REMARK VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (CONFIG_CODE)
);

COMMENT ON TABLE T_SYS_CONFIG IS '系统配置主表';

CREATE TABLE T_SYS_CONFIG_DETAIL (
    CONFIG_CODE VARCHAR2(80 CHAR) NOT NULL,
    DETAIL_CODE VARCHAR2(80 CHAR) NOT NULL,
    DETAIL_VALUE CLOB,
    REMARK VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (CONFIG_CODE, DETAIL_CODE)
);

COMMENT ON TABLE T_SYS_CONFIG_DETAIL IS '系统配置明细表';

CREATE TABLE T_HOT_RELOAD_TASK (
    TASK_ID VARCHAR2(80 CHAR) NOT NULL,
    APP_NAME VARCHAR2(100 CHAR) NOT NULL,
    ENV VARCHAR2(30 CHAR) NOT NULL,
    PATCH_NAME VARCHAR2(300 CHAR),
    PATCH_SHA256 VARCHAR2(128 CHAR),
    RELOAD_TYPE VARCHAR2(30 CHAR),
    PERSIST_ON_RESTART VARCHAR2(1 CHAR) DEFAULT 'N',
    TASK_REMARK VARCHAR2(1000 CHAR),
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (TASK_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_TASK IS '集群热重载任务主表';
CREATE INDEX IDX_HOT_RELOAD_TASK_01 ON T_HOT_RELOAD_TASK (ENV, APP_NAME);

CREATE TABLE T_HOT_RELOAD_TASK_INSTANCE (
    TASK_INSTANCE_ID VARCHAR2(80 CHAR) NOT NULL,
    TASK_ID VARCHAR2(80 CHAR) NOT NULL,
    APP_NAME VARCHAR2(100 CHAR) NOT NULL,
    ENV VARCHAR2(30 CHAR) NOT NULL,
    IP VARCHAR2(64 CHAR) NOT NULL,
    EXECUTE_TYPE VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    STATUS VARCHAR2(30 CHAR) NOT NULL,
    ERROR_CODE VARCHAR2(100 CHAR),
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    RELOAD_RESULT CLOB,
    RETRY_COUNT NUMBER(10) DEFAULT 0,
    RECEIVE_TIME TIMESTAMP,
    START_TIME TIMESTAMP,
    FINISH_TIME TIMESTAMP,
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (TASK_INSTANCE_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_TASK_INSTANCE IS '集群热重载节点执行日志表';
CREATE INDEX IDX_HOT_RELOAD_TASK_INST_01 ON T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, STATUS);
CREATE INDEX IDX_HOT_RELOAD_TASK_INST_02 ON T_HOT_RELOAD_TASK_INSTANCE (IP);
CREATE INDEX IDX_HOT_RELOAD_TASK_INST_03 ON T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, IP, EXECUTE_TYPE);

CREATE TABLE T_HOT_RELOAD_FILE (
    FILE_ID VARCHAR2(80 CHAR) NOT NULL,
    TASK_ID VARCHAR2(80 CHAR) NOT NULL,
    FILE_NAME VARCHAR2(300 CHAR),
    FILE_TYPE VARCHAR2(30 CHAR) NOT NULL,
    BEAN_NAME VARCHAR2(300 CHAR),
    CLASS_NAME VARCHAR2(500 CHAR),
    FILE_SHA256 VARCHAR2(128 CHAR),
    FILE_CONTENT BLOB NOT NULL,
    CREATED_BY VARCHAR2(50 CHAR),
    CREATED_TIME TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (FILE_ID)
);

COMMENT ON TABLE T_HOT_RELOAD_FILE IS '集群热重载补丁文件表';
CREATE INDEX IDX_HOT_RELOAD_FILE_01 ON T_HOT_RELOAD_FILE (TASK_ID);
