server:
  port: 8080

spring:
  application:
    name: arthas-cluster-hot-reload-demo
  profiles:
    active: local,mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    database: 0
  datasource:
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 1
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

arthas:
  ip: 127.0.0.1
  http-port: 8563
  output-path: ${java.io.tmpdir}/arthas-output/${spring.application.name}

hot-reload:
  redis-topic: HOT_RELOAD_TOPIC
  secret-key: demo-hot-reload
  arthas-init-wait-ms: 5000
  database-type: MYSQL
