DELETE FROM T_SYS_CONFIG_DETAIL
 WHERE CONFIG_CODE = 'RELOAD_CONFIG'
   AND DETAIL_CODE IN ('RELOAD_SERVICE', 'RELOAD_SWITCH');

DELETE FROM T_SYS_CONFIG
 WHERE CONFIG_CODE = 'RELOAD_CONFIG';

INSERT INTO T_SYS_CONFIG(CONFIG_CODE, CONFIG_NAME, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES ('RELOAD_CONFIG', '热重载配置', '集群热重载页面配置', 'system', NOW(), 'system', NOW());

INSERT INTO T_SYS_CONFIG_DETAIL(CONFIG_CODE, DETAIL_CODE, DETAIL_VALUE, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES ('RELOAD_CONFIG', 'RELOAD_SWITCH', 'Y', '热重载总开关', 'system', NOW(), 'system', NOW());

INSERT INTO T_SYS_CONFIG_DETAIL(CONFIG_CODE, DETAIL_CODE, DETAIL_VALUE, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (
    'RELOAD_CONFIG',
    'RELOAD_SERVICE',
    '[ { "appName": "cluster-hot-reload-demo", "nodeTotal": "2" } ]',
    '热重载服务下拉配置',
    'system',
    NOW(),
    'system',
    NOW()
);
