CREATE TABLE IF NOT EXISTS T_SYS_CONFIG (
    CONFIG_CODE VARCHAR(80) NOT NULL COMMENT '配置编码',
    CONFIG_NAME VARCHAR(200) COMMENT '配置名称',
    REMARK VARCHAR(1000) COMMENT '备注',
    CREATED_BY VARCHAR(50) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(50) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (CONFIG_CODE)
) COMMENT='系统配置主表';

CREATE TABLE IF NOT EXISTS T_SYS_CONFIG_DETAIL (
    CONFIG_CODE VARCHAR(80) NOT NULL COMMENT '配置编码',
    DETAIL_CODE VARCHAR(80) NOT NULL COMMENT '明细编码',
    DETAIL_VALUE TEXT COMMENT '明细值',
    REMARK VARCHAR(1000) COMMENT '备注',
    CREATED_BY VARCHAR(50) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(50) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (CONFIG_CODE, DETAIL_CODE)
) COMMENT='系统配置明细表';

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_TASK (
    TASK_ID VARCHAR(80) NOT NULL COMMENT '任务ID',
    APP_NAME VARCHAR(100) NOT NULL COMMENT '应用名称',
    ENV VARCHAR(30) NOT NULL COMMENT '运行环境',
    PATCH_NAME VARCHAR(300) COMMENT '补丁文件名称',
    PATCH_SHA256 VARCHAR(128) COMMENT '补丁文件SHA-256摘要',
    RELOAD_TYPE VARCHAR(30) COMMENT '重载类型',
    PERSIST_ON_RESTART VARCHAR(1) DEFAULT 'N' COMMENT '容器重启后是否继续保持本次重载',
    TASK_REMARK VARCHAR(1000) COMMENT '任务备注',
    CREATED_BY VARCHAR(50) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(50) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (TASK_ID),
    KEY IDX_HOT_RELOAD_TASK_01 (ENV, APP_NAME)
) COMMENT='集群热重载任务主表';

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_TASK_INSTANCE (
    TASK_INSTANCE_ID VARCHAR(80) NOT NULL COMMENT '任务实例ID',
    TASK_ID VARCHAR(80) NOT NULL COMMENT '任务ID',
    APP_NAME VARCHAR(100) NOT NULL COMMENT '应用名称',
    ENV VARCHAR(30) NOT NULL COMMENT '运行环境',
    IP VARCHAR(64) NOT NULL COMMENT '节点Pod IP',
    EXECUTE_TYPE VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '执行类型，NORMAL为正常热更，STOP_RECOVERY为停止重启自动恢复，RECOVER为服务启动恢复',
    STATUS VARCHAR(30) NOT NULL COMMENT '节点执行状态',
    ERROR_CODE VARCHAR(100) COMMENT '错误编码',
    ERROR_MESSAGE VARCHAR(2000) COMMENT '错误信息',
    RELOAD_RESULT LONGTEXT COMMENT '重载执行结果',
    RETRY_COUNT INT DEFAULT 0 COMMENT '重试次数',
    RECEIVE_TIME DATETIME COMMENT '任务接收时间',
    START_TIME DATETIME COMMENT '重载开始时间',
    FINISH_TIME DATETIME COMMENT '重载完成时间',
    CREATED_BY VARCHAR(50) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(50) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (TASK_INSTANCE_ID),
    KEY IDX_HOT_RELOAD_TASK_INST_01 (TASK_ID, STATUS),
    KEY IDX_HOT_RELOAD_TASK_INST_02 (IP),
    KEY IDX_HOT_RELOAD_TASK_INST_03 (TASK_ID, IP, EXECUTE_TYPE)
) COMMENT='集群热重载节点执行日志表';

CREATE TABLE IF NOT EXISTS T_HOT_RELOAD_FILE (
    FILE_ID VARCHAR(80) NOT NULL COMMENT '文件ID',
    TASK_ID VARCHAR(80) NOT NULL COMMENT '任务ID',
    FILE_NAME VARCHAR(300) COMMENT '文件名称',
    FILE_TYPE VARCHAR(30) NOT NULL COMMENT '文件类型',
    BEAN_NAME VARCHAR(300) COMMENT 'Spring Bean名称',
    CLASS_NAME VARCHAR(500) COMMENT '类名',
    FILE_SHA256 VARCHAR(128) COMMENT '文件SHA-256摘要',
    FILE_CONTENT LONGBLOB NOT NULL COMMENT '文件二进制内容',
    CREATED_BY VARCHAR(50) COMMENT '创建人',
    CREATED_TIME DATETIME COMMENT '创建时间',
    UPDATED_BY VARCHAR(50) COMMENT '更新人',
    UPDATED_TIME DATETIME COMMENT '更新时间',
    PRIMARY KEY (FILE_ID),
    KEY IDX_HOT_RELOAD_FILE_01 (TASK_ID)
) COMMENT='集群热重载补丁文件表';
