DELETE FROM dbo.T_SYS_CONFIG_DETAIL
 WHERE CONFIG_CODE = 'RELOAD_CONFIG'
   AND DETAIL_CODE IN ('RELOAD_SERVICE', 'RELOAD_SWITCH');

DELETE FROM dbo.T_SYS_CONFIG
 WHERE CONFIG_CODE = 'RELOAD_CONFIG';

INSERT INTO dbo.T_SYS_CONFIG(CONFIG_CODE, CONFIG_NAME, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES ('RELOAD_CONFIG', N'热重载配置', N'集群热重载页面配置', 'system', SYSDATETIME(), 'system', SYSDATETIME());

INSERT INTO dbo.T_SYS_CONFIG_DETAIL(CONFIG_CODE, DETAIL_CODE, DETAIL_VALUE, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES ('RELOAD_CONFIG', 'RELOAD_SWITCH', 'Y', N'热重载总开关', 'system', SYSDATETIME(), 'system', SYSDATETIME());

INSERT INTO dbo.T_SYS_CONFIG_DETAIL(CONFIG_CODE, DETAIL_CODE, DETAIL_VALUE, REMARK, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (
    'RELOAD_CONFIG',
    'RELOAD_SERVICE',
    N'[ { "appName": "cluster-hot-reload-demo", "nodeTotal": "2" } ]',
    N'热重载服务下拉配置',
    'system',
    SYSDATETIME(),
    'system',
    SYSDATETIME()
);
