IF OBJECT_ID('dbo.T_SYS_CONFIG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.T_SYS_CONFIG (
        CONFIG_CODE NVARCHAR(80) NOT NULL,
        CONFIG_NAME NVARCHAR(200) NULL,
        REMARK NVARCHAR(1000) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_TIME DATETIME2 NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_TIME DATETIME2 NULL,
        CONSTRAINT PK_T_SYS_CONFIG PRIMARY KEY (CONFIG_CODE)
    );
END;

IF OBJECT_ID('dbo.T_SYS_CONFIG_DETAIL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.T_SYS_CONFIG_DETAIL (
        CONFIG_CODE NVARCHAR(80) NOT NULL,
        DETAIL_CODE NVARCHAR(80) NOT NULL,
        DETAIL_VALUE NVARCHAR(MAX) NULL,
        REMARK NVARCHAR(1000) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_TIME DATETIME2 NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_TIME DATETIME2 NULL,
        CONSTRAINT PK_T_SYS_CONFIG_DETAIL PRIMARY KEY (CONFIG_CODE, DETAIL_CODE)
    );
END;

IF OBJECT_ID('dbo.T_HOT_RELOAD_TASK', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.T_HOT_RELOAD_TASK (
        TASK_ID NVARCHAR(80) NOT NULL,
        APP_NAME NVARCHAR(100) NOT NULL,
        ENV NVARCHAR(30) NOT NULL,
        PATCH_NAME NVARCHAR(300) NULL,
        PATCH_SHA256 NVARCHAR(128) NULL,
        RELOAD_TYPE NVARCHAR(30) NULL,
        PERSIST_ON_RESTART NVARCHAR(1) NULL CONSTRAINT DF_T_HOT_RELOAD_TASK_PERSIST DEFAULT 'N',
        TASK_REMARK NVARCHAR(1000) NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_TIME DATETIME2 NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_TIME DATETIME2 NULL,
        CONSTRAINT PK_T_HOT_RELOAD_TASK PRIMARY KEY (TASK_ID)
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_HOT_RELOAD_TASK_01' AND object_id = OBJECT_ID('dbo.T_HOT_RELOAD_TASK'))
BEGIN
    CREATE INDEX IDX_HOT_RELOAD_TASK_01 ON dbo.T_HOT_RELOAD_TASK (ENV, APP_NAME);
END;

IF OBJECT_ID('dbo.T_HOT_RELOAD_TASK_INSTANCE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.T_HOT_RELOAD_TASK_INSTANCE (
        TASK_INSTANCE_ID NVARCHAR(80) NOT NULL,
        TASK_ID NVARCHAR(80) NOT NULL,
        APP_NAME NVARCHAR(100) NOT NULL,
        ENV NVARCHAR(30) NOT NULL,
        IP NVARCHAR(64) NOT NULL,
        EXECUTE_TYPE NVARCHAR(20) NOT NULL CONSTRAINT DF_T_HOT_RELOAD_TASK_INST_EXEC DEFAULT 'NORMAL',
        STATUS NVARCHAR(30) NOT NULL,
        ERROR_CODE NVARCHAR(100) NULL,
        ERROR_MESSAGE NVARCHAR(2000) NULL,
        RELOAD_RESULT NVARCHAR(MAX) NULL,
        RETRY_COUNT INT NULL CONSTRAINT DF_T_HOT_RELOAD_TASK_INST_RETRY DEFAULT 0,
        RECEIVE_TIME DATETIME2 NULL,
        START_TIME DATETIME2 NULL,
        FINISH_TIME DATETIME2 NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_TIME DATETIME2 NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_TIME DATETIME2 NULL,
        CONSTRAINT PK_T_HOT_RELOAD_TASK_INSTANCE PRIMARY KEY (TASK_INSTANCE_ID)
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_HOT_RELOAD_TASK_INST_01' AND object_id = OBJECT_ID('dbo.T_HOT_RELOAD_TASK_INSTANCE'))
BEGIN
    CREATE INDEX IDX_HOT_RELOAD_TASK_INST_01 ON dbo.T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, STATUS);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_HOT_RELOAD_TASK_INST_02' AND object_id = OBJECT_ID('dbo.T_HOT_RELOAD_TASK_INSTANCE'))
BEGIN
    CREATE INDEX IDX_HOT_RELOAD_TASK_INST_02 ON dbo.T_HOT_RELOAD_TASK_INSTANCE (IP);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_HOT_RELOAD_TASK_INST_03' AND object_id = OBJECT_ID('dbo.T_HOT_RELOAD_TASK_INSTANCE'))
BEGIN
    CREATE INDEX IDX_HOT_RELOAD_TASK_INST_03 ON dbo.T_HOT_RELOAD_TASK_INSTANCE (TASK_ID, IP, EXECUTE_TYPE);
END;

IF OBJECT_ID('dbo.T_HOT_RELOAD_FILE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.T_HOT_RELOAD_FILE (
        FILE_ID NVARCHAR(80) NOT NULL,
        TASK_ID NVARCHAR(80) NOT NULL,
        FILE_NAME NVARCHAR(300) NULL,
        FILE_TYPE NVARCHAR(30) NOT NULL,
        BEAN_NAME NVARCHAR(300) NULL,
        CLASS_NAME NVARCHAR(500) NULL,
        FILE_SHA256 NVARCHAR(128) NULL,
        FILE_CONTENT VARBINARY(MAX) NOT NULL,
        CREATED_BY NVARCHAR(50) NULL,
        CREATED_TIME DATETIME2 NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_TIME DATETIME2 NULL,
        CONSTRAINT PK_T_HOT_RELOAD_FILE PRIMARY KEY (FILE_ID)
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_HOT_RELOAD_FILE_01' AND object_id = OBJECT_ID('dbo.T_HOT_RELOAD_FILE'))
BEGIN
    CREATE INDEX IDX_HOT_RELOAD_FILE_01 ON dbo.T_HOT_RELOAD_FILE (TASK_ID);
END;
